name: authentication_repository
description: Authentication repository.
version: 0.0.1

publish_to: "none"

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  http: ^1.0.0
  local_data:
    path: ../local_data

dev_dependencies:
  mockito: ^5.4.0
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
